// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyNunitWeb.Api;

#nullable disable

namespace MyNunitWeb.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251228190820_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("MyNunitWeb.Api.TestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("DurationMs")
                        .HasColumnType("REAL");

                    b.Property<string>("Message")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("TestRunId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TestRunId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TestRunId");

                    b.HasIndex("TestRunId1");

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("MyNunitWeb.Api.TestRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Failed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ignored")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Passed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.ToTable("TestRuns");
                });

            modelBuilder.Entity("MyNunitWeb.Api.TestResult", b =>
                {
                    b.HasOne("MyNunitWeb.Api.TestRun", null)
                        .WithMany("Results")
                        .HasForeignKey("TestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyNunitWeb.Api.TestRun", "TestRun")
                        .WithMany()
                        .HasForeignKey("TestRunId1");

                    b.Navigation("TestRun");
                });

            modelBuilder.Entity("MyNunitWeb.Api.TestRun", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
